# Generated by Django 4.1.7 on 2023-02-18 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemmodel',
            name='user',
        ),
        migrations.AddField(
            model_name='itemmodel',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
