# Generated by Django 4.1.7 on 2023-02-20 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_itemmodel_user_itemmodel_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmodel',
            name='count',
            field=models.IntegerField(default=100),
        ),
    ]
